commands/microceph: make sure add-osd was provided with a block dev
In case of typo, we would have wiped 4M of the provided file or
created a new one.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/snapcraft/commands/microceph b/snapcraft/commands/microceph
--- a/snapcraft/commands/microceph
+++ b/snapcraft/commands/microceph
@@ -87,6 +87,11 @@ elif [ "${1}" = "add-osd" ]; then
         exit 1
     fi
 
+    if ! [ -b "${OSD_PATH}" ]; then
+        echo "${OSD_PATH} is not a block device, aborting" >&2
+        exit 1
+    fi
+
     ceph auth get-or-create "osd.${OSD_NR}" mgr 'allow profile osd' mon 'allow profile osd' osd 'allow *' -o "${SNAP_COMMON}/data/osd/ceph-${OSD_NR}/keyring"
     ln -s "${OSD_PATH}" "${SNAP_COMMON}/data/osd/ceph-${OSD_NR}/block"
     uuidgen > "${SNAP_COMMON}/data/osd/ceph-${OSD_NR}/fsid"
